kind: pipeline
name: default

steps:
- name: build
  image: python
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
    SSH_KNOWN_HOSTS:
      from_secret: SSH_KNOWN_HOSTS
    SSH_PATH:
      from_secret: SSH_PATH
  commands:
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | ssh-add -
    - mkdir ~/.ssh/
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - wget https://github.com/boyter/scc/releases/download/v3.0.0/scc-3.0.0-x86_64-unknown-linux.zip
    - unzip scc-3.0.0-x86_64-unknown-linux.zip
    - mv scc /usr/bin
    - rm scc-3.0.0-x86_64-unknown-linux.zip

    - pip3 install jinja2 pyyaml libsass
    - python build.py

    - rm -rf repos/
    - scp -r * $SSH_PATH

trigger:
  branch:
  - main