kind: pipeline
name: default

steps:
- name: build
  image: python
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
    SSH_PORT:
      from_secret: SSH_PORT
    SSH_PATH:
      from_secret: SSH_PATH
  commands:
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | ssh-add -

    - wget https://github.com/boyter/scc/releases/download/v3.0.0/scc-3.0.0-x86_64-unknown-linux.zip
    - unzip scc-3.0.0-x86_64-unknown-linux.zip
    - mv scc /usr/bin
    - rm scc-3.0.0-x86_64-unknown-linux.zip

    - pip3 install jinja2 pyyaml libsass
    - python build.py

    - rm -rf repos/
    - scp -o "StrictHostKeyChecking no" -P $SSH_PORT -r * $SSH_PATH

trigger:
  branch:
    - main
  event:
    include:
      - push
      - cron
      - custom

